version: '3'

services:
  web_api:
    build: .
    image: rostegg/flask-api-boilerplate
    ports:
      - "5000:5000"
    container_name: web_api
    depends_on: 
      - redis

  redis:
    image: redis

